#!/bin/bash
#adds all the relevant files to git
git add git_add_script README.txt
git add quad_riblet/0 quad_riblet/system quad_riblet/constant
git add quad_riblet/run_script quad_riblet/ball_run_script quad_riblet/combine_script quad_riblet/mpi_script_interFoam.sh
git add quad_riblet/constants.dat quad_riblet/constants2.dat
